version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      testing:
        patterns:
          - "org.junit*"
          - "org.testfx*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
